/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package idv.hsiehpinghan.goraassistant.enumeration;
@SuppressWarnings("all")
/** Enumeration doc */
@org.apache.avro.specific.AvroGenerated
public enum Enumeration {
  ENUM_0, ENUM_1, ENUM_2  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Enumeration\",\"namespace\":\"idv.hsiehpinghan.goraassistant.enumeration\",\"doc\":\"Enumeration doc\",\"symbols\":[\"ENUM_0\",\"ENUM_1\",\"ENUM_2\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}

