/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package idv.hsiehpinghan.avroassistant.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(16)
@org.apache.avro.specific.AvroGenerated
public class Fixed extends org.apache.avro.specific.SpecificFixed {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"Fixed\",\"namespace\":\"idv.hsiehpinghan.avroassistant.avro\",\"size\":16}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  
  /** Creates a new Fixed */
  public Fixed() {
    super();
  }
  
  /** Creates a new Fixed with the given bytes */
  public Fixed(byte[] bytes) {
    super(bytes);
  }
}
