/*
 * This file is generated by jOOQ.
 */
package idv.hsiehpinghan.jooqassistant.jooq;


import idv.hsiehpinghan.jooqassistant.jooq.tables.Author;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JoopAssistant extends SchemaImpl {

    private static final long serialVersionUID = -1653503127;

    /**
     * The reference instance of <code>joop_assistant</code>
     */
    public static final JoopAssistant JOOP_ASSISTANT = new JoopAssistant();

    /**
     * The table <code>joop_assistant.author</code>.
     */
    public final Author AUTHOR = idv.hsiehpinghan.jooqassistant.jooq.tables.Author.AUTHOR;

    /**
     * No further instances allowed
     */
    private JoopAssistant() {
        super("joop_assistant", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR);
    }
}
