/*
 * This file is generated by jOOQ.
 */
package idv.hsiehpinghan.jooqassistant.jooq;


import idv.hsiehpinghan.jooqassistant.jooq.tables.Author;
import idv.hsiehpinghan.jooqassistant.jooq.tables.AuthorBook;
import idv.hsiehpinghan.jooqassistant.jooq.tables.Book;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqAssistant extends SchemaImpl {

    private static final long serialVersionUID = 815062585;

    /**
     * The reference instance of <code>jooq_assistant</code>
     */
    public static final JooqAssistant JOOQ_ASSISTANT = new JooqAssistant();

    /**
     * The table <code>jooq_assistant.author</code>.
     */
    public final Author AUTHOR = idv.hsiehpinghan.jooqassistant.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>jooq_assistant.author_book</code>.
     */
    public final AuthorBook AUTHOR_BOOK = idv.hsiehpinghan.jooqassistant.jooq.tables.AuthorBook.AUTHOR_BOOK;

    /**
     * The table <code>jooq_assistant.book</code>.
     */
    public final Book BOOK = idv.hsiehpinghan.jooqassistant.jooq.tables.Book.BOOK;

    /**
     * No further instances allowed
     */
    private JooqAssistant() {
        super("jooq_assistant", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            AuthorBook.AUTHOR_BOOK,
            Book.BOOK);
    }
}
