/*
 * This file is generated by jOOQ.
 */
package idv.hsiehpinghan.jooqassistant.jooq;


import idv.hsiehpinghan.jooqassistant.jooq.tables.Author;
import idv.hsiehpinghan.jooqassistant.jooq.tables.Book;
import idv.hsiehpinghan.jooqassistant.jooq.tables.BookStore;
import idv.hsiehpinghan.jooqassistant.jooq.tables.BookToBookStore;
import idv.hsiehpinghan.jooqassistant.jooq.tables.Language;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqAssistant extends SchemaImpl {

    private static final long serialVersionUID = -69861493;

    /**
     * The reference instance of <code>jooq_assistant</code>
     */
    public static final JooqAssistant JOOQ_ASSISTANT = new JooqAssistant();

    /**
     * The table <code>jooq_assistant.author</code>.
     */
    public final Author AUTHOR = idv.hsiehpinghan.jooqassistant.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>jooq_assistant.book</code>.
     */
    public final Book BOOK = idv.hsiehpinghan.jooqassistant.jooq.tables.Book.BOOK;

    /**
     * The table <code>jooq_assistant.book_store</code>.
     */
    public final BookStore BOOK_STORE = idv.hsiehpinghan.jooqassistant.jooq.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>jooq_assistant.book_to_book_store</code>.
     */
    public final BookToBookStore BOOK_TO_BOOK_STORE = idv.hsiehpinghan.jooqassistant.jooq.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>jooq_assistant.language</code>.
     */
    public final Language LANGUAGE = idv.hsiehpinghan.jooqassistant.jooq.tables.Language.LANGUAGE;

    /**
     * No further instances allowed
     */
    private JooqAssistant() {
        super("jooq_assistant", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Book.BOOK,
            BookStore.BOOK_STORE,
            BookToBookStore.BOOK_TO_BOOK_STORE,
            Language.LANGUAGE);
    }
}
