/*
 * This file is generated by jOOQ.
 */
package idv.hsiehpinghan.jooqassistant.jooq;


import idv.hsiehpinghan.jooqassistant.jooq.tables.Author;
import idv.hsiehpinghan.jooqassistant.jooq.tables.AuthorBook;
import idv.hsiehpinghan.jooqassistant.jooq.tables.Book;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq_assistant
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq_assistant.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>jooq_assistant.author_book</code>.
     */
    public static final AuthorBook AUTHOR_BOOK = AuthorBook.AUTHOR_BOOK;

    /**
     * The table <code>jooq_assistant.book</code>.
     */
    public static final Book BOOK = Book.BOOK;
}
