/*
 * This file is generated by jOOQ.
 */
package idv.hsiehpinghan.jooqassistant.jooq;


import idv.hsiehpinghan.jooqassistant.jooq.tables.Author;
import idv.hsiehpinghan.jooqassistant.jooq.tables.Book;
import idv.hsiehpinghan.jooqassistant.jooq.tables.BookStore;
import idv.hsiehpinghan.jooqassistant.jooq.tables.BookToBookStore;
import idv.hsiehpinghan.jooqassistant.jooq.tables.Language;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq_assistant
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq_assistant.author</code>.
     */
    public static final Author AUTHOR = Author.AUTHOR;

    /**
     * The table <code>jooq_assistant.book</code>.
     */
    public static final Book BOOK = Book.BOOK;

    /**
     * The table <code>jooq_assistant.book_store</code>.
     */
    public static final BookStore BOOK_STORE = BookStore.BOOK_STORE;

    /**
     * The table <code>jooq_assistant.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>jooq_assistant.language</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;
}
