# install mysql
apt-get update
apt-get install mysql-server

# install mysql-workbench
apt-get install mysql-workbench

# create database
mysql -u root -p
SHOW DATABASES;
CREATE DATABASE my_database;

# create user
CREATE USER 'thank'@'localhost' IDENTIFIED BY '%j6w1oW';
GRANT ALL PRIVILEGES ON my_database.* TO 'thank'@'localhost';
FLUSH PRIVILEGES;

# install luke
https://github.com/DmitryKey/luke/releases

