# install mysql
apt-get update
apt-get install mysql-server

# install mysql-workbench (ubuntu)
apt-get install mysql-workbench

# install mysql workbench (centos)
rpm -Uvh http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
yum update
yum install libzip-0.9-3.1.el6
yum install tinyxml
yum install mysql-workbench-community

# create database
mysql -u root -p
SHOW DATABASES;
CREATE DATABASE my_database;

# create user
CREATE USER 'thank'@'localhost' IDENTIFIED BY '%j6w1oW';
GRANT ALL PRIVILEGES ON my_database.* TO 'thank'@'localhost';
FLUSH PRIVILEGES;

# install luke
https://github.com/DmitryKey/luke/releases

# run luke
export LUKE_PATH=/home/hsiehpinghan/Downloads/luke-5.5.0-luke-release
/home/hsiehpinghan/Downloads/luke-5.5.0-luke-release/luke.sh
